### ISSUE TITLE
Example app?

### ISSUE THREAD

**Issue by blah238** [irlnathan/sails-generate-scaffold#1]
This looks interesting, but I'm having trouble visualizing what all is going on here. What are all the template files for? Do you have an example application that makes use of this? Is the goal to emulate Rails scaffolds?

Sorry if it's too soon to be bugging you with questions :)

**Comment by irlnathan** [comment]
Apologies for not seeing this earlier.  The idea at first is to illustrate a crud app in sails.  I'm definitely open to ideas.
