### ISSUE TITLE
Work in Progress?

### ISSUE THREAD

**Issue by ghost** [irlnathan/sails-generate-scaffold#2]
Very cool stuff Nathan. Was wondering is this a wip since all the controllers are empty after generation? Im using sails v0.10.0-rc8

**Comment by igncp** [comment]
Also interested, I'm actively using Sails 0.10 right now and I would help wherever I could, I really think scaffold generators would be sugar for sails.js

**Comment by ghost** [comment]
Its pretty easy to delete the controller the scaffold generates then create your own with sails generate.  Aside from that, based on some tests I ran last night, I think this module is complete and working great

**Comment by mayuroks** [comment]
Currently I had to write CRUD controller on my own. If scaffold generated basic CRUD controllers then it would be really awesome. It would kickstart my projects. Please consider this as a feature request

UPDATE:
I looked into Generator.js and and templates/action.template, I think there should be some way via command line in which we can generate CRUD controllers.
In my case, when i do this

``` bash
$ sails generate scaffold blogtest title:text body:text author:string
```

Models are generated fine BUT this is how the controller is being generated.

``` javascript
/**
 * BlogtestController
 *
 * @description :: Server-side logic for managing Blogtests
 * @help        :: See http://links.sailsjs.org/docs/controllers
 */

module.exports = {

};
```

Is there some way via command line which will help me generate CRUD controller ?

**Comment by lykmapipo** [comment]
Hi mayuroks, for scaffold to work in sails v0.10.0-rc8 i created a fork of the repo https://github.com/lykmapipo/sails-generate-scaffold.git and add a hack by which you will be able to generate actions too. I had the same problem. I also created a pull request.

**Comment by ghost** [comment]
@lykmapipo :+1:

**Comment by mayuroks** [comment]
@lykmapipo .. your fork :fork_and_knife: helps me  .. thanks guyz !!

**Comment by irlnathan** [comment]
Apologies to the late answer here.  This module requires rc8 or later.
